spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:Doseoro-for-test;MODE=MYSQL;DB_CLOSE_DELAY=-1;
    username: sa
    password:
  flyway:
    enabled: true
    encoding: UTF-8
    user: sa
    password:
