mybatis:
  type-aliases-package: com.myproject.doseoro.application
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  profiles:
    active: test
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:Doseoro-for-test
    username: sa
    password:
  servlet:
    multipart:
      location: /Users/jeongtaeung/Desktop/CODES/doseoro/src/main/resources/static/uploads/imgs
      max-request-size: 30MB
      max-file-size: 10MB
