mybatis:
  type-aliases-package: com.myproject.doseoro.application
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3307/Doseoro?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: Wjdxodnd1@
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  servlet:
    multipart:
      location: /Users/jeongtaeung/Desktop/CODES/doseoro/src/main/resources/static/uploads/imgs
      max-request-size: 30MB
      max-file-size: 10MB
