server:
  port: 1000

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3307/Doseoro?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: aa
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    user: aa
    password: 1q2w3e4r
    url: jdbc:mysql://localhost:3307/Doseoro?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  servlet:
    multipart:
      location: /Users/jeongtaeung/Desktop/CODES/doseoro/src/main/resources/static/uploads/imgs
      max-request-size: 30MB
      max-file-size: 10MB
