mybatis:
  config-location: classpath:mapper.xml
  mapper-locations: classpath:DoseoroDao.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/Doseoro?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: Wjdxodnd1@
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
    static-path-pattern: /resources/**
  servlet:
    multipart:
      enabled: true
      location: /resources/uploads/
      max-request-size: 30MB
      max-file-size: 10MB