package com.myproject.doseoro.packages.identity.handler;

import com.myproject.doseoro.global.dao.DoseoroDao;
import com.myproject.doseoro.global.error.exception.BusinessException;
import com.myproject.doseoro.packages.identity.vo.IdentityVO;
import com.myproject.doseoro.packages.identity.vo.SignUpVO;
import com.myproject.doseoro.packages.infra.session.AccessUserSessionManager;
import com.myproject.doseoro.packages.infra.mybatis.identity.IdentityMybatisService;
import lombok.RequiredArgsConstructor;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.transaction.annotation.Transactional;

import static org.assertj.core.api.Assertions.*;

@SpringBootTest
class AuthenticateUserCommandHandlerTest {

    @Autowired
    private DoseoroDao dao;
    @Autowired
    private PasswordEncoder passwordEncoder;
    @Autowired
    private AccessUserSessionManager accessUserSessionManager;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    public void setIdentityTable() {
        String query = "create table if not exists t_identity\n" +
                "(\n" +
                "seq bigint generated by default as identity,\n" +
                "id varchar(64) not null,\n" +
                "email varchar(200) not null, \n" +
                "password varchar(200) not null, \n" +
                "name varchar(20) not null, \n" +
                "nick_name varchar(25) not null, \n" +
                "phone varchar(14) not null, \n" +
                "forgot_pw_question varchar(100) not null, \n" +
                "forgot_pw_answer varchar(100) not null, \n" +
                "location varchar(100) null, \n" +
                "dong varchar(10) null, \n" +
                "si varchar(10) null, \n" +
                "dou varchar(10) null, \n" +
                "provider varchar(100) null, \n" +
                "sns_id varchar(50) null \n" +
                ");";
        jdbcTemplate.execute(query);
    }

    @Test
    @DisplayName("유저는 로그인을 할 수 있다.")
    @Transactional
    public void loginSuccessCommandHandler() {
        // given
        IdentityMybatisService repository = new IdentityMybatisService(dao, passwordEncoder);
        CreateUserIdentityCommandHandler createUserIdentityCommandHandler = new CreateUserIdentityCommandHandler(repository);
        AuthenticateUserCommandHandler sut = new AuthenticateUserCommandHandler(repository, accessUserSessionManager);

        SignUpVO signUpUser = new SignUpVO(
                "7777777",
                "abcdefg@naver.com",
                "aa",
                "홍길동",
                "길동이",
                "010-1234-5678",
                "좋아하는 추억",
                "많은 추억"
        );
        createUserIdentityCommandHandler.handle(signUpUser);

        IdentityVO loginUser = new IdentityVO(
                "7777777",
                "abcdefg@naver.com",
                "aa",
                "홍길동",
                "길동이",
                "010-1234-5678",
                "좋아하는 추억",
                "많은 추억",
                null
        );

        // when
        boolean actual = sut.handle(loginUser);

        // then
        assertThat(actual).isTrue();
    }

    @Test
    @DisplayName("유저는 유저 정보를 틀리게 입력하면 로그인을 할 수 없다.")
    @Transactional
    public void loginFailureCommandHandler() {
        // given
        IdentityMybatisService repository = new IdentityMybatisService(dao, passwordEncoder);
        CreateUserIdentityCommandHandler createUserIdentityCommandHandler = new CreateUserIdentityCommandHandler(repository);
        AuthenticateUserCommandHandler sut = new AuthenticateUserCommandHandler(repository, accessUserSessionManager);

        SignUpVO signUpUser = new SignUpVO(
                "7777777",
                "abcdefg@naver.com",
                "aa",
                "홍길동",
                "길동이",
                "010-1234-5678",
                "좋아하는 추억",
                "많은 추억"
        );
        createUserIdentityCommandHandler.handle(signUpUser);

        IdentityVO loginUser = new IdentityVO(
                "7770777",
                "abcdef@naver.com",
                "aa",
                "홍길동",
                "길동이",
                "010-1234-5678",
                "좋아하는 추억",
                "많은 추억",
                null
        );

        // when
        // then
        Assertions.assertThrows(BusinessException.class, ()-> sut.handle(loginUser));
    }
}
